[workspace]
members = ["crates/*"]
resolver = "2"

[profile.release]
opt-level = 3
lto = "thin"

[profile.debug-lite]
inherits = "dev"
incremental = false
opt-level = 0
debug = 1
lto = "none"

[profile.release-lite]
inherits = "release"
opt-level = 2

[profile.debug-opt]
inherits = "release"
debug = 2
debug-assertions = true
incremental = true

[profile.docker]
inherits = "release"
# strip = "symbols" # Not supported in the workspace toolchain version

[patch.crates-io]
solana-transaction-status = { git = 'https://github.com/step-finance/solana.git', ref = "c1bbc390d8050931f324a833fabde00e638ca9a9" }
solana-geyser-plugin-interface = { git = 'https://github.com/step-finance/solana.git', ref = "c1bbc390d8050931f324a833fabde00e638ca9a9" }
solana-logger = { git = 'https://github.com/step-finance/solana.git', ref = "c1bbc390d8050931f324a833fabde00e638ca9a9" }
solana-program = { git = 'https://github.com/step-finance/solana.git', ref = "c1bbc390d8050931f324a833fabde00e638ca9a9" }
solana-metrics = { git = 'https://github.com/step-finance/solana.git', ref = "c1bbc390d8050931f324a833fabde00e638ca9a9" }
